name: brute-force-integration

services:
  app-migrator:
    build:
      dockerfile: migration.Dockerfile
    env_file:
      - "./integration.env"
    depends_on:
      - db
    restart: on-failure
    networks:
      - anti-bruteforce-integration-network

  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - "./integration.env"
    ports:
      - "6379:${REDIS_PORT}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--maxmemory", "${REDIS_MAXMEMORY}", "--maxmemory-policy", "${REDIS_MAXMEMORY_POLICY}"]
    volumes:
      - redis-data:/data
    networks:
      - anti-bruteforce-integration-network

  db:
    image: postgres:15-alpine3.17
    env_file:
      - "./integration.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - anti-bruteforce-integration-network

volumes:
  postgres_volume:
  redis-data:

networks:
  anti-bruteforce-integration-network:
    driver: bridge
